name = "Nanoid"
uuid = "649b5ee6-231f-4350-86a5-2b05c0e3780e"
authors = ["Reinaldy Rafli <aldy505@tutanota.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
